# language: python
# python: 3.5
# dist: trusty
# sudo: required
# addons:
#     apt:
#         packages:
#             qemu
#             qemu-system-arm
#             gcc-arm-linux-gnueabihf
os:
    osx
install:
    - brew install qemu
    - brew install pygobject3 --with-python3 gtk+3
    - python3 -m pip install -r requirements-macos.txt
    - python3 -m pip install pyinstaller
    - pyinstaller pibox-installer-macos.spec
