before_install:
- openssl aes-256-cbc -K $encrypted_af8ee76d875e_key -iv $encrypted_af8ee76d875e_iv -in travis_secrets.tar.enc -out travis_secrets.tar -d
- tar xvf travis_secrets.tar
- chmod 600 pibox_installer_ci_rsa

matrix:
  include:
  - os: osx
    language: generic
    install:
    # Package pibox-installer
    - brew install qemu zoidbergwill/python/python35
    - brew install pygobject3 --with-python3 gtk+3
    - python3 -m pip install -r requirements-macos.txt
    - python3 -m pip install pyinstaller
    - pyinstaller pibox-installer-macos.spec

    # Sign application
    # - security create-keychain -p mysecretpassword build.keychain
    # - security default-keychain -s build.keychain
    # - security unlock-keychain -p mysecretpassword build.keychain
    # - security import pibox-installer.p12 -k build.keychain -P $MACOS_CERTIFICATE_PASSWORD -T /usr/bin/codesign
    # - codesign -s pibox-installer dist/pibox-installer.app
    - codesign -s - dist/pibox-installer.app

    # Install create-dmg
    - npm install --global create-dmg
    - create-dmg dist/pibox-installer.app
    - mv pibox-installer-0.0.0.dmg pibox-installer-nightly.dmg

    # Send dmg
    - scp -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa pibox-installer-nightly.dmg pibox_ci@buildbot.wan.bsf-intranet.org:/srv/repos/pibox/$(date +"%Y-%m-%d")/pibox-installer-macos.zip

  - os: linux
    language: python
    python: 3.4
    dist: trusty
    sudo: required
    virtualenv:
      system_site_packages: true
    addons:
      apt:
        packages:
          qemu
          qemu-system-arm
          python3-gi
          python3-gi-cairo
          python3-cairo
          gir1.2-gtk-3.0
          libdbus-1-dev
          libdbus-glib-1-dev
          libffi-dev
          build-essential
          libssl-dev
          python-dev
    script:
    - pip3 install -r requirements-linux.txt
    - pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
    - pyinstaller pibox-installer-linux.spec
    - cat build/pibox-installer-linux/warnpibox-installer-linux.txt
    - scp -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa dist/pibox-installer pibox_ci@buildbot.wan.bsf-intranet.org:/srv/repos/pibox/$(date +"%Y-%m-%d")/pibox-installer-linux
