---
- name: restart Kiwix
  shell: echo "packages moved, requesting kiwix restart"
  notify: restart kiwix
  tags: move-content

- name: Add CSS for package icon
  lineinfile:
    dest: /var/www/static/cards.css
    line: '.card.zim_{{ item|splitext|first|replace(".", "\.") }} { background-image: url("http://{{ kiwix_fqdn }}/raw/{{ item }}/meta/Illustration_48x48@1"); }'
    insertafter: EOF
    state: present
  with_items: '{{ ansible_local.config.packages | default(omit) }}'
  when: ansible_local.config.packages | length
  tags: ['move-content', 'rename']
