---
- name: Install Network-Manager
  apt:
    name: network-manager
    state: latest
    autoremove: yes
    autoclean: yes
  tags: master

- name: Setup eth0 connection
  command: nmcli connection add ifname eth0 type ethernet autoconnect yes save yes
  tags: master
