---
- name: Install the user-provided resources
  become: yes
  become_user: "{{ username }}"
  command: "{{ edupi_env }}/bin/python3 {{ edupi_root }}/manage.py import-from-folder --delete {{ edupi_resources_path }}"
  tags: move-content

- name: remove user provided resources (already imported)
  become: yes
  become_user: "{{ username }}"
  file:
    path: "{{ edupi_resources_path }}"
    state: absent
  tags: move-content
