---
- import_tasks: clean_apt.yml
  tags: setup

- name: Install dependencies (tex, for MathRenderer)
  apt:
    name: texlive,texlive-fonts-recommended,texlive-lang-greek,texlive-latex-recommended,texlive-latex-extra,build-essential,dvipng,ocaml,cjk-latex
    state: latest
    autoremove: yes
    autoclean: yes
  tags: setup

- import_tasks: clean_apt.yml
  tags: setup

- name: Install dependencies (PHP)
  environment:
    RUNLEVEL: 1
  apt:
    name: php{{ php_version }}-fpm,php{{ php_version }}-sqlite3,php{{ php_version }}-intl,php{{ php_version }}-mbstring,php{{ php_version }}-xml,php{{ php_version }}-curl,php{{ php_version }}-gd
    state: latest
    autoremove: yes
    autoclean: yes
  tags: setup

- import_tasks: disable_service.yml
  vars:
    service: php{{ php_version }}-fpm
  tags: setup

- name: change PHP7 settings to allow file uploads up to 5MiB
  copy:
    src: 90-wikifundi.ini
    dest: /etc/php/{{ php_version }}/fpm/conf.d/90-wikifundi.ini
  tags: setup

- name: change PHP7 config
  template:
    src: www.conf.j2
    dest: /etc/php/{{ php_version }}/fpm/pool.d/www.conf
  tags: setup

- import_tasks: clean_apt.yml
  tags: setup

- name: Install dependencies (others)
  environment:
    RUNLEVEL: 1
  apt:
    name: git,vim,unzip,imagemagick,libicu-dev,ffmpeg,librsvg2-bin,poppler-utils,memcached,lua5.1,python3,locales,sqlite3,fonts-freefont-ttf,ttf-unifont,exiv2,libtiff-tools,libvips-tools
    state: latest
    autoremove: yes
    autoclean: yes
  tags: setup

- import_tasks: disable_service.yml
  vars:
    service: memcached
  tags: setup

- import_tasks: clean_apt.yml
  tags: setup

# locale en_US.UTF-8 already installed on system role

- name: hack to avoid thumbs generation error for PDF with errors
  shell: mv /usr/bin/gs /usr/bin/gs9-20 ; echo '/usr/bin/gs9-20 -sstdout=%stderr $@' > /usr/bin/gs ; chmod a+x /usr/bin/gs
  tags: setup

- name: make cache dir
  file:
    dest: "/dev/shm/mw"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
  tags: setup

- name: make sure directories exists
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ wikifundi_root }}"
    - "{{ mediawiki_root }}"
  tags: setup

- name: download mediawiki
  get_url:
    url: "{{ mirror }}/dev/mediawiki-1.36.1__with-extensions.tar.bz2"
    dest: /tmp/mediawiki.tar.bz2
  tags: setup

- name: extract mediawiki
  command: tar -C {{ mediawiki_root }} -x --strip-components=1 -f /tmp/mediawiki.tar.bz2
  tags: setup

- name: change ownership of folders
  file:
    path: "{{ mediawiki_root }}/{{ item }}"
    owner: www-data
    group: www-data
    state: directory
    recurse: yes
  with_items:
    - skins
    - cache
  tags: setup

- name: download composer
  get_url:
    url: "{{ mirror }}/dev/composer-2.phar"
    dest: "{{ mediawiki_root }}/composer.phar"
  tags: setup

- name: update composer config to prevent network header mismatch
  command: php composer.phar config -g repo.packagist composer https://packagist.org
  args:
    chdir: "{{ mediawiki_root }}"
  tags: setup

- name: update composer config to prevent network header mismatch (2)
  command: php composer.phar config -g github-protocols https ssh
  args:
    chdir: "{{ mediawiki_root }}"
  tags: setup

- name: install composer
  command: php composer.phar install --no-dev
  args:
    chdir: "{{ mediawiki_root }}"
  tags: setup

- name: link FreeSans font without extension
  command: ln -s FreeSans.ttf FreeSans
  args:
    chdir: /usr/share/fonts/truetype/freefont
  tags: setup

- name: fix permission on folder
  file:
    path: "{{ mediawiki_root }}/extensions"
    owner: www-data
    group: www-data
    state: directory
    recurse: yes
  tags: setup

- name: Copy image assets
  copy:
    src: "{{ item }}"
    dest: "{{ wikifundi_root }}/{{ item }}"
  with_items:
    - cc-by-sa.png
    - A_WikiAfrica_project.png
    - favicon.ico
    - logo.png
    - logo-sq.png
  tags: setup

- name: copy php conf for nginx
  template:
    src: php.conf.j2
    dest: /etc/nginx/conf.d/php.conf
  tags: setup

# Configuration files
- name: set mediawiki main config file
  copy:
    src: LocalSettings.php
    dest: "{{ mediawiki_root }}/LocalSettings.php"
  tags: setup

- name: copy blank debug and mirroring config files
  copy:
    src: empty.php
    dest: "{{ mediawiki_root }}/LocalSettings.{{ item }}.php"
  with_items:
    - debug
    - mirroring
  tags: setup
